version: '3'
services:
  ms-sql-server:
    image: mcr.microsoft.com/mssql/server:2019-latest
    environment:
        ACCEPT_EULA: "Y"
        SA_PASSWORD: "Passw0rd2022"
        MSSQL_PID: Express
    ports:
    - "1433:1433"
  flyingcars:
    build: .
    environment:
      Server: "ms-sql-server"
      Port: "1433"
      Name: "flyingcardb"
      Username: "SA"
      Password: "Passw0rd2022"
    ports:
    - "8080:80"
    depends_on:
    - ms-sql-server
